services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=absensi'
      - 'POSTGRES_PASSWORD=absensi'
      - 'POSTGRES_USER=absensi'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
      - ./:/docker-entrypoint-initdb.d/
